[package]
authors = [""]
compiler_version = "0.8.0"

[dependencies]
ecrecover = { tag = "v0.8.0", git = "https://github.com/colinnielsen/ecrecover-noir" }
proof = { tag = "main", git = "https://github.com/aragonzkresearch/noir-trie-proofs" }
# noir_bigint = { tag = "v0.1.0", git = "https://github.com/shuklaayush/noir-bigint" }
